/**
 * Routes untuk custom pages & menu navigasi WSO2 portal.
 *
 * Source markdown disimpan di: <portal>/pages/<slug>/source.md
 * Render output (jaggery) di:  <portal>/pages/<slug>/index.jag
 * Menu config:                  <portal>/conf/customMenu.json
 */
const express = require('express');
const fs = require('fs-extra');
const path = require('path');

const SLUG_RE = /^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/;

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
}

function renderJag(title, html) {
  return `<%
// Auto-generated by WSO2 Admin Panel — DO NOT EDIT.
// Source markdown: ./source.md
%>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${escapeHtml(title)}</title>
  <link rel="stylesheet" href="/devportal/site/public/styles/default.css">
</head>
<body class="custom-page">
  <article class="custom-page__content">
${html}
  </article>
</body>
</html>
`;
}

// Mini markdown renderer (heading, paragraph, bold/italic/link/code).
// Cukup untuk konten dasar. Ganti dengan `marked` kalau butuh lebih lengkap.
function md(src) {
  const lines = String(src).split(/\r?\n/);
  const out = [];
  let inP = [];
  const flushP = () => { if (inP.length) { out.push(`<p>${inline(inP.join(' '))}</p>`); inP = []; } };

  function inline(s) {
    s = escapeHtml(s);
    s = s.replace(/`([^`]+)`/g, '<code>$1</code>');
    s = s.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
    s = s.replace(/\*([^*]+)\*/g, '<em>$1</em>');
    s = s.replace(/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g, '<a href="$2" rel="noopener">$1</a>');
    return s;
  }

  for (const raw of lines) {
    const l = raw.trim();
    if (!l) { flushP(); continue; }
    const h = l.match(/^(#{1,6})\s+(.*)$/);
    if (h) { flushP(); out.push(`<h${h[1].length}>${inline(h[2])}</h${h[1].length}>`); continue; }
    if (/^[-*]\s+/.test(l)) {
      flushP();
      const items = [l];
      while (lines.length && /^[-*]\s+/.test((lines[0] || '').trim())) items.push(lines.shift().trim());
      out.push('<ul>' + items.map((i) => `<li>${inline(i.replace(/^[-*]\s+/, ''))}</li>`).join('') + '</ul>');
      continue;
    }
    inP.push(l);
  }
  flushP();
  return out.join('\n');
}

function safeSlug(s) {
  if (typeof s !== 'string' || !SLUG_RE.test(s)) return null;
  return s;
}

function build(opts) {
  const { PATHS, requireAuth, resolvePortal } = opts;
  const router = express.Router();

  const portalRoot = (portal) => path.join(PATHS.base, portal);
  const pagesDir = (portal) => path.join(portalRoot(portal), 'pages');
  const menuFile = (portal) => path.join(portalRoot(portal), 'conf', 'customMenu.json');

  // ── List pages ───────────────────────────────────────
  router.get('/pages/:portal', requireAuth, (req, res) => {
    const portal = resolvePortal(req.params.portal);
    if (!portal) return res.status(400).json({ success: false, message: 'Portal tidak valid' });
    const dir = pagesDir(portal);
    fs.ensureDirSync(dir);
    const slugs = fs.readdirSync(dir).filter((f) => fs.statSync(path.join(dir, f)).isDirectory());
    const pages = slugs.map((slug) => {
      const meta = path.join(dir, slug, 'meta.json');
      let title = slug;
      try { if (fs.existsSync(meta)) title = JSON.parse(fs.readFileSync(meta, 'utf8')).title || slug; } catch (_) {}
      return { slug, title };
    });
    res.json({ success: true, pages });
  });

  // ── Get single page ──────────────────────────────────
  router.get('/pages/:portal/:slug', requireAuth, (req, res) => {
    const portal = resolvePortal(req.params.portal);
    const slug = safeSlug(req.params.slug);
    if (!portal || !slug) return res.status(400).json({ success: false, message: 'Parameter tidak valid' });

    const dir = path.join(pagesDir(portal), slug);
    if (!fs.existsSync(dir)) return res.status(404).json({ success: false, message: 'Page tidak ditemukan' });

    const source = fs.existsSync(path.join(dir, 'source.md'))
      ? fs.readFileSync(path.join(dir, 'source.md'), 'utf8')
      : '';
    const meta = fs.existsSync(path.join(dir, 'meta.json'))
      ? JSON.parse(fs.readFileSync(path.join(dir, 'meta.json'), 'utf8'))
      : { title: slug };
    res.json({ success: true, slug, title: meta.title || slug, content: source });
  });

  // ── Save / create page ───────────────────────────────
  router.put('/pages/:portal/:slug', requireAuth, (req, res) => {
    const portal = resolvePortal(req.params.portal);
    const slug = safeSlug(req.params.slug);
    if (!portal || !slug) return res.status(400).json({ success: false, message: 'Slug harus huruf kecil/angka/dash' });

    const { title, content } = req.body || {};
    if (typeof title !== 'string' || typeof content !== 'string') {
      return res.status(400).json({ success: false, message: 'Title dan content wajib diisi' });
    }
    if (title.length > 200 || content.length > 200000) {
      return res.status(400).json({ success: false, message: 'Title atau content terlalu panjang' });
    }

    try {
      const dir = path.join(pagesDir(portal), slug);
      fs.ensureDirSync(dir);
      fs.writeFileSync(path.join(dir, 'source.md'), content, 'utf8');
      fs.writeFileSync(path.join(dir, 'meta.json'), JSON.stringify({ title, updatedAt: new Date().toISOString() }, null, 2));
      fs.writeFileSync(path.join(dir, 'index.jag'), renderJag(title, md(content)), 'utf8');
      res.json({ success: true, message: `Page ${slug} disimpan. Restart WSO2 untuk apply.` });
    } catch (e) {
      res.status(500).json({ success: false, message: e.message });
    }
  });

  // ── Delete page ──────────────────────────────────────
  router.delete('/pages/:portal/:slug', requireAuth, (req, res) => {
    const portal = resolvePortal(req.params.portal);
    const slug = safeSlug(req.params.slug);
    if (!portal || !slug) return res.status(400).json({ success: false, message: 'Parameter tidak valid' });

    const dir = path.join(pagesDir(portal), slug);
    if (!fs.existsSync(dir)) return res.status(404).json({ success: false, message: 'Page tidak ditemukan' });

    try {
      fs.removeSync(dir);
      res.json({ success: true, message: `Page ${slug} dihapus` });
    } catch (e) {
      res.status(500).json({ success: false, message: e.message });
    }
  });

  // ── Menu config ──────────────────────────────────────
  router.get('/menu/:portal', requireAuth, (req, res) => {
    const portal = resolvePortal(req.params.portal);
    if (!portal) return res.status(400).json({ success: false, message: 'Portal tidak valid' });
    const f = menuFile(portal);
    let items = [];
    if (fs.existsSync(f)) {
      try { items = JSON.parse(fs.readFileSync(f, 'utf8')).items || []; }
      catch (_) { items = []; }
    }
    res.json({ success: true, items });
  });

  router.put('/menu/:portal', requireAuth, (req, res) => {
    const portal = resolvePortal(req.params.portal);
    if (!portal) return res.status(400).json({ success: false, message: 'Portal tidak valid' });

    const { items } = req.body || {};
    if (!Array.isArray(items) || items.length > 50) {
      return res.status(400).json({ success: false, message: 'Items harus array (≤ 50)' });
    }
    for (const it of items) {
      if (!it || typeof it.label !== 'string' || typeof it.href !== 'string'
          || it.label.length > 50 || it.href.length > 200) {
        return res.status(400).json({ success: false, message: 'Item menu tidak valid' });
      }
    }

    try {
      const f = menuFile(portal);
      fs.ensureDirSync(path.dirname(f));
      fs.writeFileSync(f, JSON.stringify({ items, updatedAt: new Date().toISOString() }, null, 2));
      res.json({ success: true, message: 'Menu disimpan' });
    } catch (e) {
      res.status(500).json({ success: false, message: e.message });
    }
  });

  return router;
}

module.exports = { build };
